### ISSUE TITLE
게시글 관리 페이지 구현

### ISSUE THREAD

**Issue by bang-star** [bang-star/fastcampus-project-board-admin#35]
#21 에서 준비한 내용을 토대로, 게시글 관리 페이지를 구현한다

## TODO

* [ ] 게시판 프로젝트
   * [ ] API 호출이 가능하도록 인증 설정 변경하기
   * [ ] Data Rest API 설정 검토하기
   * [ ] 테스트용 계정 추가하기
* [ ] 게시글, 댓글 상세 내용을 보기 위한 모달(Modal) 추가
* [ ] 기본 에러 페이지 구현

## Reference

- #21 게시글 관리 페이지 기능 테스트 정의
